### ISSUE TITLE
HomeKit does not receive state

### ISSUE THREAD

**Issue by Tyraenor** [CptMW/homebridge-ghoma#1] opened 2018-01-02 20:53 UTC
The accessory in HomeKit does not get the current state of the outlet. As soon as the home app is reopened, or the iPhone is coming from standby, the state in the home app is "off".
This behavior prevents the use of automation, as without the current state, timed switching does not working.

The webserver included does show the correct state, so it is just not being reported to HomeKit.

**Comment by CptMW** [comment] 2018-12-01 05:51
Did not look into the project for a while and see the issue is quite old. However I fixed in anyway. If you are still interested please try again.

**Closed** 2018-12-01 05:50 UTC
